<a href="https://colab.research.google.com/github/dhvanipatel000/CE090_ML_Labs/blob/main/ML_Lab3_CE090.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Implementation of Naive bayes classifier

from sklearn import preprocessing
from sklearn.naive_bayes import GaussianNB, MultinomialNB

weather = ['Sunny', 'Sunny', 'Overcast', 'Rainy', 'Rainy','Rainy', 'Overcast',
'Sunny', 'Sunny', 'Rainy', 'Sunny', 'Overcast', 'Overcast', 'Rainy']

temp = ['Hot','Hot','Hot','Mild','Cool','Cool','Cool','Mild',
'Cool','Mild','Mild','Mild','Hot','Mild']

play=['No','No','Yes','Yes','Yes','No','Yes','No','Yes',
'Yes','Yes','Yes','Yes','No']
le = preprocessing.LabelEncoder()

weather_encoded = le.fit_transform(weather)
print("Weather: ", weather_encoded)

Weather:  [2 2 0 1 1 1 0 2 2 1 2 0 0 1]


In [ ]:
temp_encoded = le.fit_transform(temp)
label = le.fit_transform(play)

print("Temp: ",temp_encoded)
print("Play: ",label)

Temp:  [1 1 1 2 0 0 0 2 0 2 2 2 1 2]
Play:  [0 0 1 1 1 0 1 0 1 1 1 1 1 0]


In [ ]:
features = tuple(zip(weather_encoded, temp_encoded))
print("Features: ",features)

Features:  ((2, 1), (2, 1), (0, 1), (1, 2), (1, 0), (1, 0), (0, 0), (2, 2), (2, 0), (1, 2), (2, 2), (0, 2), (0, 1), (1, 2))


In [ ]:
model = MultinomialNB()
model.fit(features,label)

MultinomialNB()

In [ ]:
predicted = model.predict([[0,2]])
print(predicted)
     

[1]


In [ ]:

predicted = model.predict([[2,2],[2,1]])
print(predicted)

[1 1]


1.5 Exercise: Manually calculate output for the following cases and compare it
with system’s output.
1.5.1 (1) Will you play if the temperature is ‘Hot’ and weather is ‘overcast’?
1.5.2 (2) Will you play if the temperature is ‘Mild’ and weather is ‘Sunny’?

In [ ]:
predicted = model.predict([[0,1]])
manual = 1
print("Predicted= ",predicted,"\nManual= ",manual,"\nPredicted = Manual? ",predicted[0]==manual)

Predicted=  [1] 
Manual=  1 
Predicted = Manual?  True


In [ ]:
predicted = model.predict([[2,2]])
manual = 1
print("Predicted= ",predicted,"\nManual= ",manual,"\nPredicted = Manual? ",predicted[0]==manual)

Predicted=  [1] 
Manual=  1 
Predicted = Manual?  True


Iris Dataset:
2_NB_Classifier_Iris_2Classes

In [ ]:
import numpy as np
from sklearn import datasets
from sklearn.naive_bayes import GaussianNB

iris = datasets.load_iris()
print("Features: ",iris.feature_names)
print("Labels: ",iris.target_names)
print("\nData shape: ",iris.data.shape)
print("\nTarget shape: ",iris.target.shape)

print("\nData type: ",type(iris.data))
newdata = iris.data[50:,:]
newtarget = iris.target[50:]
print("New data shape: ",newdata.shape)
print("\nNew target shape: ",newtarget.shape)
     

Features:  ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
Labels:  ['setosa' 'versicolor' 'virginica']

Data shape:  (150, 4)

Target shape:  (150,)

Data type:  <class 'numpy.ndarray'>
New data shape:  (100, 4)

New target shape:  (100,)


In [ ]:
from sklearn.model_selection import train_test_split

data_train, data_test, target_train, target_test = train_test_split(newdata,newtarget, test_size=0.30, random_state=5)
import numpy as np
gnb = GaussianNB()

gnb.fit(data_train, target_train)

target_pred = gnb.predict(data_test)

In [ ]:
from sklearn import metrics

print("Accuracy: ",metrics.accuracy_score(target_test,target_pred))

Accuracy:  0.9


In [ ]:
from sklearn.metrics import confusion_matrix
confusion_matrix(target_test, target_pred)
     

array([[16,  1],
       [ 2, 11]])

In [ ]:
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
precision = precision_score(target_test, target_pred)
recall = recall_score(target_test, target_pred)
print('precision: {}'.format(precision))
print('recall: {}'.format(recall))

precision: 0.8888888888888888
recall: 0.9411764705882353


3_NB_Classifier_Iris_3Classes:

In [ ]:
#Import scikit-learn dataset library
from sklearn import datasets
from sklearn.naive_bayes import GaussianNB
#Load dataset
iris = datasets.load_iris()
# print the names of the 13 features
print("Features: ", iris.feature_names)
# print the label type of wine(class_0, class_1, class_2)
print("Labels: ", iris.target_names)
# print data(feature)shape
iris.data.shape

Features:  ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
Labels:  ['setosa' 'versicolor' 'virginica']


(150, 4)

In [ ]:
#import the necessary module
from sklearn.model_selection import train_test_split
#split data set into train and test sets
data_train, data_test, target_train, target_test = train_test_split(iris.data,
iris.target, test_size = 0.30, random_state = 10)

import numpy as np
gnb = GaussianNB()
#Train the model using the training sets
gnb.fit(data_train, target_train)
#Predict the response for test dataset
target_pred = gnb.predict(data_test)

In [ ]:
#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics
# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(target_test, target_pred))

Accuracy: 1.0


In [ ]:
#Import confusion_matrix from scikit-learn metrics module for confusion_matrix
from sklearn.metrics import confusion_matrix
confusion_matrix(target_test, target_pred)

array([[14,  0,  0],
       [ 0, 17,  0],
       [ 0,  0, 14]])

In [ ]:
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
precision = precision_score(target_test, target_pred, average=None)
recall = recall_score(target_test, target_pred, average=None)
print('precision: {}'.format(precision))
print('recall: {}'.format(recall))

precision: [1. 1. 1.]
recall: [1. 1. 1.]


Exercise
4) 76<=Rollnumber<=100: #Task 1: Try the algo on Dataset2 - OneHotEncoding of features:
and Train test Division 75%-25% #Task 2: Apply algorithm on wine dataset - LabelEncoding of
features: and Train test Division 80%-20%

In [ ]:
from sklearn import datasets
from sklearn.naive_bayes import GaussianNB
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder,OneHotEncoder

#Load data
datasets = pd.read_csv('/content/drive/MyDrive/Dataset2.csv')
print("\nData: \n",datasets)
print("\nData statistics\n",datasets.describe())


Data: 
    Outlook Temp Wind Humidity Class
0        R    H    F   Normal     N
1        R    H    T     High     N
2        O    H    F   Normal     Y
3        S    M    F   Normal     N
4        S    M    F   Normal     Y
5        S    M    T      Low     Y
6        O    C    T   Normal     Y
7        R    C    F   Normal     Y
8        R    C    F      Low     Y
9        S    M    F     High     Y
10       R    M    T     High     Y
11       O    M    T      Low     Y
12       O    H    F   Normal     Y
13       S    M    T   Normal     N

Data statistics
        Outlook Temp Wind Humidity Class
count       14   14   14       14    14
unique       3    3    2        3     2
top          R    M    F   Normal     Y
freq         5    7    8        8    10


In [ ]:
dummies1 = pd.get_dummies(datasets.Outlook)
dummies2 = pd.get_dummies(datasets.Temp)
dummies3 = pd.get_dummies(datasets.Wind)
dummies4 = pd.get_dummies(datasets.Humidity)
dummies1
dummies2
dummies3
dummies4

High  Low  Normal
0      0    0       1
1      1    0       0
2      0    0       1
3      0    0       1
4      0    0       1
5      0    1       0
6      0    0       1
7      0    0       1
8      0    1       0
9      1    0       0
10     1    0       0
11     0    1       0
12     0    0       1
13     0    0       1

In [ ]:
merged = pd.concat([datasets,dummies1,dummies2,dummies3,dummies4],axis='columns')
merged

Outlook Temp Wind Humidity Class  O  R  S  C  H  M  F  T  High  Low  Normal
0        R    H    F   Normal     N  0  1  0  0  1  0  1  0     0    0       1
1        R    H    T     High     N  0  1  0  0  1  0  0  1     1    0       0
2        O    H    F   Normal     Y  1  0  0  0  1  0  1  0     0    0       1
3        S    M    F   Normal     N  0  0  1  0  0  1  1  0     0    0       1
4        S    M    F   Normal     Y  0  0  1  0  0  1  1  0     0    0       1
5        S    M    T      Low     Y  0  0  1  0  0  1  0  1     0    1       0
6        O    C    T   Normal     Y  1  0  0  1  0  0  0  1     0    0       1
7        R    C    F   Normal     Y  0  1  0  1  0  0  1  0     0    0       1
8        R    C    F      Low     Y  0  1  0  1  0  0  1  0     0    1       0
9        S    M    F     High     Y  0  0  1  0  0  1  1  0     1    0       0
10       R    M    T     High     Y  0  1  0  0  0  1  0  1     1    0       0
11       O    M    T      Low     Y  1  0  0  0  0  1  0  1     0    1       0
12       O    H    F   Normal     Y  1  0  0  0  1  0  1  0     0    0       1
13       S    M    T   Normal     N  0  0  1  0  0  1  0  1     0    0       1

In [ ]:
final = merged.drop(['Outlook','Temp','Wind','Humidity'],axis='columns')
final

Class  O  R  S  C  H  M  F  T  High  Low  Normal
0      N  0  1  0  0  1  0  1  0     0    0       1
1      N  0  1  0  0  1  0  0  1     1    0       0
2      Y  1  0  0  0  1  0  1  0     0    0       1
3      N  0  0  1  0  0  1  1  0     0    0       1
4      Y  0  0  1  0  0  1  1  0     0    0       1
5      Y  0  0  1  0  0  1  0  1     0    1       0
6      Y  1  0  0  1  0  0  0  1     0    0       1
7      Y  0  1  0  1  0  0  1  0     0    0       1
8      Y  0  1  0  1  0  0  1  0     0    1       0
9      Y  0  0  1  0  0  1  1  0     1    0       0
10     Y  0  1  0  0  0  1  0  1     1    0       0
11     Y  1  0  0  0  0  1  0  1     0    1       0
12     Y  1  0  0  0  1  0  1  0     0    0       1
13     N  0  0  1  0  0  1  0  1     0    0       1

In [ ]:
onehotencoder = OneHotEncoder()
o = onehotencoder.fit_transform(datasets.Outlook.values.reshape(-1,1)).toarray()
o

array([[0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.]])

In [ ]:
onehotencoder = OneHotEncoder()
t = onehotencoder.fit_transform(datasets.Temp.values.reshape(-1,1)).toarray()
t

array([[0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
onehotencoder = OneHotEncoder()
w = onehotencoder.fit_transform(datasets.Wind.values.reshape(-1,1)).toarray()
w

array([[1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.]])

In [ ]:
onehotencoder = OneHotEncoder()
h = onehotencoder.fit_transform(datasets.Humidity.values.reshape(-1,1)).toarray()
h

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.]])

In [ ]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()
x = final.drop('Class',axis='columns')
x

O  R  S  C  H  M  F  T  High  Low  Normal
0   0  1  0  0  1  0  1  0     0    0       1
1   0  1  0  0  1  0  0  1     1    0       0
2   1  0  0  0  1  0  1  0     0    0       1
3   0  0  1  0  0  1  1  0     0    0       1
4   0  0  1  0  0  1  1  0     0    0       1
5   0  0  1  0  0  1  0  1     0    1       0
6   1  0  0  1  0  0  0  1     0    0       1
7   0  1  0  1  0  0  1  0     0    0       1
8   0  1  0  1  0  0  1  0     0    1       0
9   0  0  1  0  0  1  1  0     1    0       0
10  0  1  0  0  0  1  0  1     1    0       0
11  1  0  0  0  0  1  0  1     0    1       0
12  1  0  0  0  1  0  1  0     0    0       1
13  0  0  1  0  0  1  0  1     0    0       1

In [ ]:
y = final.Class
y

0     N
1     N
2     Y
3     N
4     Y
5     Y
6     Y
7     Y
8     Y
9     Y
10    Y
11    Y
12    Y
13    N
Name: Class, dtype: object

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(
x, y, train_size = 0.75, random_state=90)

In [ ]:
from sklearn import metrics
model.fit(x_train,y_train)
pred = model.predict(x_test)
print(pred)
accuracy = metrics.accuracy_score(y_test,pred)
precision=metrics.precision_score(y_test,pred,average=None)
recall = metrics.recall_score(y_test,pred,average=None)
print('Accuracy: {}'.format(accuracy))
print('precision: {}'.format(precision))
print('recall: {}'.format(recall))

['Y' 'Y' 'Y' 'Y']
Accuracy: 0.75
precision: [0.   0.75]
recall: [0. 1.]


/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
# dfOneHot = pd.DataFrame(x, columns = ["Outlook_"+str(int(i)) for i in range(datasets.shape[1]-2)])
# df = pd.concat([datasets, dfOneHot], axis=1) #column
# #droping the country column
# df= df.drop(['Outlook'], axis=1)
# #printing to verify
# print(df.head())

In [ ]:
# from sklearn import metrics
# from sklearn.model_selection import train_test_split
# datasets.keys(),datasets.target

In [ ]:
model.score(x,y)

0.8571428571428571

In [ ]:
model.predict([[0,1,0,0,0,1,1,0,0,0,1]])

/usr/local/lib/python3.8/dist-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but GaussianNB was fitted with feature names
  warnings.warn(


array(['N'], dtype='<U1')

In [ ]:
model.predict([[0,0,1,1,0,0,0,1,1,0,0]])

/usr/local/lib/python3.8/dist-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but GaussianNB was fitted with feature names
  warnings.warn(


array(['Y'], dtype='<U1')

#Task 2: Apply algorithm on wine dataset LabelEncoding of features: and Train test Division 80% − 20%



In [ ]:
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.naive_bayes import GaussianNB
from sklearn import preprocessing
from sklearn.metrics import confusion_matrix
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
import pandas as pd
from sklearn import datasets

wine = datasets.load_wine()
df_wine = pd.DataFrame(wine.data, columns=wine.feature_names)
df_wine['target'] = pd.Series(wine.target)

# data = df_wine.apply(LabelEncoder().fit_transform)
# print(data['alcohol'])
data = OneHotEncoder().fit_transform(df_wine).toarray()
print(data)

from sklearn.model_selection import train_test_split

# using random state as last 2 digits of my Roll No
data_train, data_test, target_train, target_test = train_test_split(data,wine['target'],train_size=0.8,test_size=0.2, random_state=90)


[[0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 1. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]]


In [ ]:
from sklearn import metrics
gnb = GaussianNB()
gnb.fit(data_train, target_train)

target_pred = gnb.predict(data_test)
accuracy = metrics.accuracy_score(target_test, target_pred)
precision = metrics.precision_score(target_test, target_pred, average=None)
recall = metrics.recall_score(target_test, target_pred, average=None)

print('Accuracy: {}'.format(accuracy))
print('precision: {}'.format(precision))
print('recall: {}'.format(recall))

Accuracy: 1.0
precision: [1. 1. 1.]
recall: [1. 1. 1.]
